name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version: ["version-2-0", "version-2-2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Nim and Nimble
        run: |
          curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
          env MAKE="make -j4" ARCH_OVERRIDE=x64 NIM_COMMIT=${{ matrix.nim-version }} \
            QUICK_AND_DIRTY_COMPILER=1 QUICK_AND_DIRTY_NIMBLE=1 CC=gcc \
            bash build_nim.sh nim csources dist/nimble NimBinaries
          echo '${{ github.workspace }}/nim/bin' >> $GITHUB_PATH

      - name: Run tests
        run: |
          nim --version
          nimble --version
          gcc --version
          nimble install -y --depsOnly
          find tests -name 'test_*.nim' | awk '{print "include \"" $0 "\""}' > tests/test_all.nim
          nim r tests/test_all.nim